### ISSUE TITLE
Wheels for series 16 require python 3.10, not compatible with official Odoo image

### ISSUE THREAD

**Issue by keshrath** [acsone/setuptools-odoo#101]
The current 3.10 standard is not compatible with Odoo's official Docker image. This currently means that none of the OCA modules can be installed on this Docker image.

Docker: https://github.com/odoo/docker/tree/master/16.0

Code: https://github.com/acsone/setuptools-odoo/blob/master/setuptools_odoo/core.py#L128

![image](https://user-images.githubusercontent.com/4851083/203849075-ab2fbd90-2384-4d3a-94ef-ddca0db21a3e.png)

**Comment by sbidoul** [comment]
Ah, this is annoying.

The official Odoo image is based on debian bullseye which has python 3.9.

The reason setuptools-odoo requires python>=3.10 for Odoo 16 is that OCA tests with python 3.10, and that was decided because Odoo SA's runbot tests with python 3.10 and odoo.sh also runs with python 3.10 (I think these run on Ubuntu Jammy, not sure).

So yeah, I don't see a great solution for this, except lobbying Odoo to release a docker image that uses python 3.10? 

Maybe @d-fence can provide insight into this.

**Comment by kongrattapong** [comment]
I have the same problem, Is there any progress on this issues? :thinking:

**Comment by sbidoul** [comment]
It's unlikely OCA will change the minimum supported python version that far in the 16.0 cycle.
You can consider building your own Odoo image based on ubuntu jammy by adapting the [Odoo Dockerfile](https://github.com/odoo/docker/tree/master/16.0).
