### ISSUE TITLE
odoo namespace not populated when pip installed addons are present (10.0)

### ISSUE THREAD

**Issue by Fenkiou** [acsone/setuptools-odoo#11]
Usually, to have a clean dev environment, I do the following steps:
- create a virtualenv
- clone odoo sources
- install requirements with pip `pip install -r requirements.txt`
- link odoo in python env `python setup.py develop`

After this, I can:
```
➔ python
Python 2.7.13 (default, Dec 18 2016, 07:03:39)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import odoo
>>> dir(odoo)
['SUPERUSER_ID', '_', '__builtins__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', 'addons', 'api', 'cli', 'conf', 'evented', 'exceptions', 'fields', 'http', 'loglevels', 'models', 'modules', 'multi_process', 'netsvc', 'os', 'osv', 'registry', 'release', 'report', 'service', 'sql_db', 'sys', 'time', 'tools', 'workflow']
>>>
```

I use https://wheelhouse.odoo-community.org/ to install OCA addons with pip. But when installing any addons from the wheelhouse, all modules from odoo package are missing:
```
➔ pip install odoo10-addon-auditlog
➔ python                                     
Python 2.7.13 (default, Dec 18 2016, 07:03:39)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import odoo
>>> dir(odoo)
['__doc__', '__name__', '__path__', 'addons']
>>>
```

**EDIT, RETESTED, NOT WORKING EITHER:** However, if I clone server-tools and install auditlog (`python setup.py install/develop`) from the setup folder, the problem doesn't appear...

I don't know why this happen, this is not related to #10 (in fact it is I think) because even after applying the patch proposed, the behavior remains the same.

**NOTE:** This is not a real issue as odoo works as expected, the problem is that I use vim that use my virtualenv to retrieve definitions from odoo and if I install any OCA addon with pip, vim can't find odoo definitions anymore as they're not exported

**Comment by sbidoul** [comment]
What you observe is correct. Thanks for reporting it.

In the situation you describe (which is a very common one), you have the `odoo.addons` namespace package (and therefore the `odoo` too) "sourced" from 2 directories:
- one in your odoo sources clone, where you have `odoo/__init__.py` which exports all kind of stuff.
- one in `$VIRTUAL_ENV/lib/python2.7/site-packages/odoo` which is created when pip installing an addon package, that one having no `__init__.py`, or an empty one.

You could have more directories if you `python setup.py develop` or `pip install -e` some addons from source.

When you have odoo only, `import odoo` finds odoo's `__init__.py` and executes it. When there is odoo/addons in site_packages it does not import it automatically because it is somehow "satisfied" to have found something in site packages.

We are actually living a bit in a grey zone here. Per setuptools documentation, it is forbidden to have code in the `__init__.py` of a namespace package . This makes sense as a ns package can be provided by many directories, so python cannot determine which `__init__.py` to run, or which one to preserve when installing them in site_packages. `odoo.addons` is correct in that respect. `odoo` however contains code in it's `__init__.py`. 

Whether `import odoo` will run `odoo`'s `__init__.py` automatically depends on `sys.path` order.

The workaround is to run `__import__('pkg_resources').declare_namespace('odoo.addons')` before `import odoo`. You might even be able to do that in your vimrc (let me know how if you try and succeed with that).

#10 is a different manifestation of the same problem, and https://github.com/odoo/odoo/pull/15718 implements the same workaround.

For v11, I'll try to find a more robust approach with Odoo (cc/ @sle-odoo), it may depend on the target python version (things may be slightly different in python 3). Or it may involve populating `odoo` with some explicit function call instead of relying on `__import__('pkg_resources').declare_namespace('odoo.addons')` magic. 

I hope this clarifies things a bit. I'll keep this issue open for future reference.

**Comment by Fenkiou** [comment]
@sbidoul, thanks for your explanations.

I'll check how I can tell vim to do this, because if I open vim in odoo directory, it is able to find definitions, but not outside the directory.

**Comment by sbidoul** [comment]
Glad you have a workaround. I'll close then. 

#10 will track the issue and there is nothing we can do in setuptools-odoo anyway.
