### ISSUE TITLE
[feature] Bundle install all addons in a repo

### ISSUE THREAD

**Issue by dreispt** [acsone/setuptools-odoo#13]
I wish the packaging tool also created a top `setup.py` for a "meta package" installing all addons in that repo.

The goal is to be able to run `pip install https://github.com/owner/repo/archive/10.0.zip` and have the addons in that repo installed in my environment.

Does this make any sense?

**Comment by sbidoul** [comment]
I considered that but concluded it was out of scope for setuptools-odoo, because it makes too many assumptions on repo structure and such.

It is however implemented in OCA/maintainer-tools [here](https://github.com/OCA/maintainer-tools/blob/08fa7d02716de875b0afc033debad37a0cffd567/tools/bdist_all_wheels.py#L152-L170).

And it generates all odoo(8|9|10)-addon**s**-*.whl (notice the plural addons) in https://wheelhouse.odoo-community.org/oca-simple.

**Comment by dreispt** [comment]
Nice! That should do the trick, thanks!
