### ISSUE TITLE
Static installation (no -e) loses data files

### ISSUE THREAD

**Issue by simahawk** [acsone/setuptools-odoo#20]
#19 showed that we can install addons statically (no editable mode + git clone).
The issue is that python installation works but odoo one no. Because...
```
# odoo -u foo
[...]
IOError: File not found: foo/security/ir.model.access.csv
```

[This doc section](https://setuptools-odoo.readthedocs.io/en/latest/#packaging-multiple-addons) says that some setuptools flags like `include_package_data` should be automatically handled but I don't see them in the auto-generated setup files. Also, AFAIR such flags rely on MANIFEST.in but there's no such file.

Shouldn't we include such files explicitly for every repo?

**Comment by sbidoul** [comment]
The setup keywords are injected [here](https://github.com/acsone/setuptools-odoo/blob/680ac2881e09f82765aaf0ec795e97ec47877ffa/setuptools_odoo/core.py#L331-L349). This code triggers when the `odoo_addon` keyword is present in `setup.py`.

It is actually [setuptools-git](https://pypi.python.org/pypi/setuptools-git), which is a [dependency of setuptools-odoo](https://github.com/acsone/setuptools-odoo/blob/680ac2881e09f82765aaf0ec795e97ec47877ffa/setup.py#L34), that finds the package data by looking at all files in the packages that are under git control. So indeed installing from a tarball that is disconnected from git will not work unless you add a MANIFEST.in.

Note that installing from a proper source distribution tarball (build with python setup.py sdist) does work because that one includes the .egg-info metadata directory. 

Also note that in the future, I would like to use setuptools-scm instead of setuptools-git because it is part of pypa and supports other vcses. But at this point it does not support symlinks.

**Comment by sbidoul** [comment]
What is your use case with tarballs, btw?

**Comment by simahawk** [comment]
I see. Well, my aim is to be able to get rid of git clone and skip the release step (package on pypi or alike) at the same time. But I guess I'm desiring too much, isn't it? :sweat_smile:

**Comment by sbidoul** [comment]
To release we do, `pip wheel -r requirements.txt -d wheel-dir`. It gives you a bunch of wheels you can deploy without git (nor internet) access. Does that help in your scenario?

**Comment by simahawk** [comment]
well I guess we can do that on build time include this folder in our docker image. Is that what you do?
Then what? You make pip [find those wheels there](http://wheel.readthedocs.io/en/stable/#usage) instead of fetching from pypi I guess.
/cc @guewen

**Comment by sbidoul** [comment]
Exactly that, yes.

**Comment by simahawk** [comment]
I found a way here https://github.com/OCA/website-cms/pull/34

**Comment by simahawk** [comment]
Well, potentially ALL files. Or at least all the ones that are not ignored by .gitignore.
But I've never seen files contained in odoo modules that should not be there...
I'd use even a `*.*` to make sure we include everything :P

As for the scenario: would be great if we can make a call. Thanks!
I'll poke you on either tomorrow or on Monday via IRC or hangout, ok?

**Comment by sbidoul** [comment]
Ok. Hangout preferably.

**Comment by sbidoul** [comment]
Installing from sources disconnected from git should be from a proper sdist. Also discussed in #24. So closing this one. Feel free to reopen if more discussion is needed.
