### ISSUE TITLE
Specify python dependency at specific version

### ISSUE THREAD

**Issue by eLBati** [acsone/setuptools-odoo#37]
It may happen that some OCA module needs a python package at specific version, different from the latest one.

The real use case:
[l10n_it_fatturapa](https://github.com/OCA/l10n-italy/blob/6493c0b367ef194dc0d19e20ea33d8a197e66f2a/l10n_it_fatturapa/__manifest__.py) needs `PyXB==1.2.5`, but, when you install it with pip from pypi, PyXB is installed at latest version (`1.2.6`), which does not work with `l10n_it_fatturapa`.

Can this be solved by using `install_requires` in [setup.py](https://github.com/OCA/l10n-italy/blob/6493c0b367ef194dc0d19e20ea33d8a197e66f2a/setup/l10n_it_fatturapa/setup.py)? Will this file be later overwritten by `OCA-git-bot`?

Thanks

**Comment by sbidoul** [comment]
@eLBati this can be done with [external_dependencies_override](https://github.com/acsone/setuptools-odoo#controlling-setuptools-odoo-behaviour) as explained in the documentation.

I really really advise against pinning versions in addons, however, except as a temporary workaround. Because you will force downstream users to use outdated version of libraries and potentially create version conflicts in the future.

**Comment by sbidoul** [comment]
setup.py will *not* be overwritten by the oca bot.

**Comment by sbidoul** [comment]
BTW, see also https://github.com/odoo/odoo/pull/25549 for an upstream solution.

**Comment by eLBati** [comment]
@sbidoul thanks a lot
