### ISSUE TITLE
How to handle the case of viivakoodi python dependency which needs to import barcode when using the task setuptools-odoo-get-requirements of pre-commit?

### ISSUE THREAD

**Issue by jcdrubay** [acsone/setuptools-odoo#48]
- python external_dependencies needs the value `barcode`
- the requirements needs `viivakoodi`
- but with the oca pre-commit configuration, setuptools-odoo-get-requirements  renders `barcode` in the requirements file

**Comment by sbidoul** [comment]
@jcdrubay since Odoo 13, you can put PyPI project names in external_dependencies. This is the recommended way as it facilitates discovery of these dependencies, for humans and machines alike.

Alternatively, or if you need to further declare version specifiers for the dependency, you can add [overrides](https://github.com/acsone/setuptools-odoo#controlling-setuptools-odoo-behaviour) in `setup.py`.

**Comment by jcdrubay** [comment]
Thanks @sbidoul
