### ISSUE TITLE
for odoo_addons type packages allow dev version adjustments too 

### ISSUE THREAD

**Issue by realjo** [acsone/setuptools-odoo#9]
For odoo_addon type packages with a single module a nice feature of setuptools_odoo is that it determines the number of commits since the version was modified in __openerp__.py or if there are uncommitted changes when the module is in git and extends the version of the python package by either ".dev1" or ".99.dev%d" % commit_count.

However this nice feature is not available when packaging multiple odoo modules into a single python package. It would be nice to add it there too, possibly enabled by a setup keyword.

I implemented it as a proof of concept into setup.py of a multi-module odoo_addons package, you might get the idea (iterating over all modules and counting the commits in total), but I think before integration into setuptools_odoo, the code in setuptools_odoo would need some reorgananisation to simplify both use cases:

```python
import os
import setuptools

# setuptools_odoo
from setuptools_odoo.manifest import is_installable_addon
from setuptools_odoo.git_postversion import get_git_postversion

# determine all the included modules
addon_dirs = []
addons_dir = 'odoo_addons'
addons = os.listdir(addons_dir)
for addon in addons:
    addon_dir = os.path.join(addons_dir, addon)
    if is_installable_addon(addon_dir):
        addon_dirs.append(addon_dir)

# determine the number of commits after last version change over
# all modules and sum them up
commit_count = 0
for addon_dir in addon_dirs:
    last_version = get_git_postversion(addon_dir)
    parts = last_version.split('.99.dev')
    if len(parts) == 2:
        commit_count += int(parts[1])
    elif last_version.endswith('.dev1'):
        commit_count = -1
        break
    else:
        pass

# determine version extension in the style of a singel odoo addon
if commit_count == 0:
    version_ext = ''
elif commit_count == -1:
    version_ext = '.dev1'
else:
    version_ext = '.99.dev%d' % commit_count

setuptools.setup(
    name='odoo-addon-example',
    version='9.0.1.0.1%s' % version_ext,
    setup_requires=[
        'setuptools-odoo',
    ],
    odoo_addons=True,
)
```

**Comment by sbidoul** [comment]
@realjo thanks a lot for this proposal.

The limited scope of setuptools-odoo is to help avoid redundancies between the Odoo manifest files and setup.py (such as dependencies and the version). 

Since there is not (yet) a well established tradition of maintaining addons versions in the Odoo Community, setuptools-odoo tries to go the extra mile for this part (and facilitate automatic distribution on places such as wheelhouse.odoo-community.org).

When packaging a set of addons, there is no Odoo manifest providing a version. That's why in this case the version must be provided with the usual setup.py keyword and setuptool-odoo does not make any attempt to touch it.

In this light, I tend to think your proposal is out of scope for setuptools-odoo. 

Actually, what you are proposing is already implemented by tools such as pbr (note I've note checked setuptools-odoo and pbr are compatible).

**Comment by realjo** [comment]
no problem, I can understand your point.
